### ISSUE TITLE
Cypress integration broken: The deleteScreenshot 'task' event has not been registered in the setupNodeEvents method. You must register it before using cy.task()

### ISSUE THREAD

**Issue by taylor-schneider** [uktrade/cypress-image-diff#155]
I have followed the [cypress integration guide](https://github.com/uktrade/cypress-image-diff/blob/main/docs/Cypress%20integration.md) but I get an error when trying to use the compareSnapshot() function:

Below is my test:

```
import React from 'react'
import Rating from '../src/Components/Recipe/Rating/Rating'

describe('<Rating />', () => {
  it('renders', () => {
    const recipe_json = {
      "rating": 5,
      "reviews": [
        {
            "author": "@Jim",
            "comment": "It was dank!",
            "rating": 4.5
        }
      ]    
    }

    var rating = Rating(recipe_json)

    cy.mount(rating)

    cy.get('.Rating').compareSnapshot('component-testing', 0.2)

  })
})
```

And here is the error I see in the cypress ui

![image](https://github.com/uktrade/cypress-image-diff/assets/67472065/4fb4818c-e0a5-41a6-ab59-7e99ff8f9514)

Here is the stack trace:

```
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:151207:80)
From previous event:
    at Context.task (http://localhost:8080/__cypress/runner/cypress_runner.js:151193:15)
    at wrapped (http://localhost:8080/__cypress/runner/cypress_runner.js:160852:43)
From Your Spec Code:
    at <unknown> (http://localhost:8080/__cypress/src/vendors-node_modules_cypress-image-diff-js_dist_command_js-node_modules_cypress_react18_dist_-991c01.js:36:10)
    at Context.cypressRecurse (http://localhost:8080/__cypress/src/vendors-node_modules_cypress-image-diff-js_dist_command_js-node_modules_cypress_react18_dist_-991c01.js:271:20)
    at getRet (http://localhost:8080/__cypress/runner/cypress_runner.js:145230:20)
    at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:18744:23)
    at Promise.attempt.Promise.try (http://localhost:8080/__cypress/runner/cypress_runner.js:16018:29)
    at Context.thenFn (http://localhost:8080/__cypress/runner/cypress_runner.js:145241:63)
    at Context.then (http://localhost:8080/__cypress/runner/cypress_runner.js:145490:21)
    at wrapped (http://localhost:8080/__cypress/runner/cypress_runner.js:160860:19)
```

**Comment by natsuki-engr** [comment]
I had same problem.
It's likely that you have `cypress/plguin/index.js`, right? The plugins file is deprecated from 10.0.0, and you must use `setupNodeEvents` in `cypress.config.js` (or `cypress.config.ts`).
> This function was added in Cypress version 10.0.0 to replace the deprecated.

https://docs.cypress.io/guides/references/configuration#Resolved-Configuration


This is my `cypress.config.js`. This works for me now.
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
      const getCompareSnapshotsPlugin = require('cypress-image-diff-js/dist/plugin')
      getCompareSnapshotsPlugin(on, config)
    },
  },
});

```

**Comment by PippoRaimondi** [comment]
Like @natsuki-engr suggested above, could you share some code around your setup?

**Comment by biswabose1992** [comment]
Hi @natsuki-engr 
Try using `return getCompareSnapshotsPlugin(on, config)` it will solve the issue

**Comment by sakilandeswari** [comment]
HI,

I am facing the issue reported here.. any solution?
my project is in typescript and nx project which has multiple mono repos
